import Head from "next/head";
import MapBox from "../components/MapBox";
import styles from "../styles/Home.module.css";
import { Panos } from "../components/Panos";
import Switcher from "../components/Switcher";
import { useAppStore } from "../stores";
import { MapProvider } from "react-map-gl/mapbox";

export default function Home() {
    const mainPano = useAppStore((state) => state.mainPano);
		return (
			<MapProvider>
				<div className={styles.container}>
					<Head>
						<title>Create Next App</title>
						<meta name="description" content="Generated by create next app" />
						<link rel="icon" href="/favicon.ico" />
						{/* Stylesheet links moved to _document.tsx */}
					</Head>

					<main className={styles.main}>
						<div id="map" className={mainPano ? styles.area : styles.full}>
							<MapBox />
						</div>
						<div id="pano" className={!mainPano ? styles.area : styles.full}>
							<Panos />
						</div>
						<Switcher />
					</main>
				</div>
			</MapProvider>
		);
}
